class default_theme:
    pet_theme_name      = "Default AxT"
    pet_button_relief   = "flat"
    pet_border          = "0"
    pet_hover           = "13"
    pet_text_colour     = "white"
    pet_bg_colour       = "#FFC7EA"
    pet_button_colour   = "#DB7699"
    pet_button_pressed  = "#BD6584"
    pet_button_hover    = "#EF81A7"

class default_dark:
    pet_theme_name      = "Default AxT Dark"
    pet_button_relief   = "flat"
    pet_border          = "0"
    pet_hover           = "13"
    pet_text_colour     = "white"
    pet_bg_colour       = "#7D4267"
    pet_button_colour   = "#C76485"
    pet_button_pressed  = "#964B64"
    pet_button_hover    = "#AF5874"

class matra_os:
    pet_theme_name      = "MatraOS"
    pet_button_relief   = "flat"
    pet_border          = "0"
    pet_hover           = "13"
    pet_text_colour     = "white"
    pet_bg_colour       = "#15091A"
    pet_button_colour   = "#2F153C"
    pet_button_pressed  = "#612687"
    pet_button_hover    = "#612687"

class matra_os_b:
    pet_theme_name      = "Matra OS Orange"
    pet_button_relief   = "flat"
    pet_border          = "0"
    pet_hover           = "13"
    pet_text_colour     = "white"
    pet_bg_colour       = "#1A100A"
    pet_button_colour   = "#975826"
    pet_button_pressed  = "#CC7734"
    pet_button_hover    = "#CC7734"

class retro_95:
    pet_theme_name      = "Old School 95"
    pet_button_relief   = "raised"
    pet_border          = "1"
    pet_hover           = "9"
    pet_text_colour     = "black"
    pet_bg_colour       = "#008080"
    pet_button_colour   = "#C3C3C3"
    pet_button_pressed  = "#E2E2E2"
    pet_button_hover    = "#E2E2E2"
